baseURL: "https://rphi.uk/"
title: _rphi
languageCode: en-gb
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: _rphi
  description: "You've reached the home of Rob Phipps on the internet."
  keywords: [Blog, Portfolio, PaperMod]
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "_rphi"
    #icon: /apple-touch-icon.png
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Howdy howdy \U0001F44B"
    Strapline: "You've reached the home of Rob Phipps on the internet."
    Content: "I'm an experienced systems engineer with a focus on application integrations, networks and automation. [More about me →](/about)"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/_rphi"
    - name: github
      url: "https://github.com/rphi"
    - name: linkedin
      url: "https://www.linkedin.com/in/rphi/"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 10
    - identifier: projects
      name: projects
      url: /tags/projects/
      weight: 20
    - identifier: contact
      name: contact
      url: /contact/
      weight: 20
    # - identifier: search
    #   name: search
    #   url: /search/
    #   weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai